### ISSUE TITLE
Players can fly when resource pack loaded

### ISSUE THREAD

**Issue by c1oudychan** [SwagSteve/SafeLoad#3]
I think it because `p.setAllowFlight(true);` in `onJoin` listener

**Comment by SwagSteve** [comment]
I am unable to replicate this issue.
`p.setAllowFlight(true);` stops loading players who are floating from being kicked for flying.

Please provide information such as the version, and steps to reproduce the issue.

**Comment by SwagSteve** [comment]
A workaround for this issue has been introduced in 1.2 which allows the server admin to disable the fly-kick bypass. This workaround may not be necessary as this issue isn't confirmed
