### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by Legendmanj** [SwagSteve/SafeLoad#6]
would be a ggs if the mod got updated to 1.21 (;

**Comment by SwagSteve** [comment]
There's no need to update the plugin to version 1.21.

As of version 1.21 server resouce packs are now downloaded & loaded on the client before joining the server, thus meaning that the player will connect regularly as if they weren't using a resource pack (with no time spent in the server whilst the pack is loading).

This makes this plugin pointless as its purpose was to fix this issue, and so it is no longer being updated.
